name: Build, Initialize Seats

on:
  push:
    branches:
      - testingDev

jobs:
  build-and-initialize:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Build API
        run: ./mvnw clean package

      - name: Start Application
        run: |
          # Start the Spring Boot application in the background
          java -jar target/flight-bookings-0.0.1-SNAPSHOT.jar &
          # Give the application enough time to start
          sleep 30

      - name: Initialize Seats
        run: |
          curl -X POST "$API_URL"

        env:
          API_URL: http://localhost:8080/api/v1/seat/initialize